RealmID = 1
LoginDatabaseInfo     = "db;3306;legion;legionpass;auth"
CharacterDatabaseInfo = "db;3306;legion;legionpass;characters"
HotfixDatabaseInfo    = "db;3306;legion;legionpass;hotfixes"
WorldDatabaseInfo     = "db;3306;legion;legionpass;world"
