CREATE DATABASE IF NOT EXISTS auth DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS characters DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS world DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON auth.* TO 'legion'@'%';
GRANT ALL PRIVILEGES ON characters.* TO 'legion'@'%';
GRANT ALL PRIVILEGES ON world.* TO 'legion'@'%';


FLUSH PRIVILEGES;
